### ISSUE TITLE
Export to package also the esm version

### ISSUE THREAD

**Issue by DarioDaF** [fabiospampinato/jsonc-simple-parser#1]
It would be nice if the package contained also the esm version with browser compliant imports (with file extension) so one could import it in test and other enviroments from a CDN like:
```
import JSONC from 'https://cdn.jsdelivr.net/npm/jsonc-simple-parser@2.2.1/dist/index.js';
```
Even directly from the browser or any web page.
In case let me know if you are not used to multiple compiles and other stuff like that, I'm neither but I could give it a try if you are ok then with publishing it that way.

**Comment by jimaek** [comment]
Have you tried using the automated ESM feature? 
https://cdn.jsdelivr.net/npm/jsonc-simple-parser@2.2.1/dist/+esm

**Comment by fabiospampinato** [comment]
I'll eventually make this esm-only, but I'm not really interested on whether it's importable directly in the browser or not, I guess one would need to bundle the library, or the library should have no dependencies, for that to work. @jimaek's solutions seems what you are looking for.

**Comment by DarioDaF** [comment]
Thanks a lot didn't even know about this feature (unpkg.com seems not to have it) it works perfectly even better than `jsonc-parser@3.2.0/lib/esm` that has the problem of extensions
